# -*- coding:utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class DiplomaType(object):
  DIPLOMA_OTHER = 0
  DIPLOMA_XIAOXUE = 1
  DIPLOMA_CHUZHONG = 2
  DIPLOMA_ZHONGZHUAN = 3
  DIPLOMA_ZHONGJI = 4
  DIPLOMA_DAZHUAN = 5
  DIPLOMA_GAOZHONG = 6
  DIPLOMA_BENKE = 7
  DIPLOMA_SHUOSHI = 8
  DIPLOMA_MBA = 9
  DIPLOMA_EMBA = 10
  DIPLOMA_BOSHI = 11
  DIPLOMA_BOSHIHOU = 12

  _VALUES_TO_NAMES = {
    0: "DIPLOMA_OTHER",
    1: "DIPLOMA_XIAOXUE",
    2: "DIPLOMA_CHUZHONG",
    3: "DIPLOMA_ZHONGZHUAN",
    4: "DIPLOMA_ZHONGJI",
    5: "DIPLOMA_DAZHUAN",
    6: "DIPLOMA_GAOZHONG",
    7: "DIPLOMA_BENKE",
    8: "DIPLOMA_SHUOSHI",
    9: "DIPLOMA_MBA",
    10: "DIPLOMA_EMBA",
    11: "DIPLOMA_BOSHI",
    12: "DIPLOMA_BOSHIHOU",
  }

  _NAMES_TO_VALUES = {
    "DIPLOMA_OTHER": 0,
    "DIPLOMA_XIAOXUE": 1,
    "DIPLOMA_CHUZHONG": 2,
    "DIPLOMA_ZHONGZHUAN": 3,
    "DIPLOMA_ZHONGJI": 4,
    "DIPLOMA_DAZHUAN": 5,
    "DIPLOMA_GAOZHONG": 6,
    "DIPLOMA_BENKE": 7,
    "DIPLOMA_SHUOSHI": 8,
    "DIPLOMA_MBA": 9,
    "DIPLOMA_EMBA": 10,
    "DIPLOMA_BOSHI": 11,
    "DIPLOMA_BOSHIHOU": 12,
  }

class EduSystemType(object):
  EDU_SYSTEM_QUANRIZHI = 1
  EDU_SYSTEM_JINXIU = 2

  _VALUES_TO_NAMES = {
    1: "EDU_SYSTEM_QUANRIZHI",
    2: "EDU_SYSTEM_JINXIU",
  }

  _NAMES_TO_VALUES = {
    "EDU_SYSTEM_QUANRIZHI": 1,
    "EDU_SYSTEM_JINXIU": 2,
  }

