# -*- coding:utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
import ipin.rpc.etl.common_type.ttypes


from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class JdIncRaw(object):
  """
  Attributes:
   - incName: 公司名称
   - incIndustry: 行业
   - incType: 公司类型
   - incScale: 公司规模
   - incIntro: 公司介绍
   - incUrl: 公司ｕｒｌ
   - incLocation: 公司地址
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'incName', None, None, ), # 1
    (2, TType.STRING, 'incIndustry', None, None, ), # 2
    (3, TType.STRING, 'incType', None, None, ), # 3
    (4, TType.STRING, 'incScale', None, None, ), # 4
    (5, TType.STRING, 'incIntro', None, None, ), # 5
    (6, TType.STRING, 'incUrl', None, None, ), # 6
    (7, TType.STRING, 'incLocation', None, None, ), # 7
  )

  def __init__(self, incName=None, incIndustry=None, incType=None, incScale=None, incIntro=None, incUrl=None, incLocation=None,):
    self.incName = incName
    self.incIndustry = incIndustry
    self.incType = incType
    self.incScale = incScale
    self.incIntro = incIntro
    self.incUrl = incUrl
    self.incLocation = incLocation

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.incName = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.incIndustry = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.incType = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.incScale = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.incIntro = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRING:
          self.incUrl = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.incLocation = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdIncRaw')
    if self.incName is not None:
      oprot.writeFieldBegin('incName', TType.STRING, 1)
      oprot.writeString(self.incName.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incIndustry is not None:
      oprot.writeFieldBegin('incIndustry', TType.STRING, 2)
      oprot.writeString(self.incIndustry.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incType is not None:
      oprot.writeFieldBegin('incType', TType.STRING, 3)
      oprot.writeString(self.incType.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incScale is not None:
      oprot.writeFieldBegin('incScale', TType.STRING, 4)
      oprot.writeString(self.incScale.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incIntro is not None:
      oprot.writeFieldBegin('incIntro', TType.STRING, 5)
      oprot.writeString(self.incIntro.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incUrl is not None:
      oprot.writeFieldBegin('incUrl', TType.STRING, 6)
      oprot.writeString(self.incUrl.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incLocation is not None:
      oprot.writeFieldBegin('incLocation', TType.STRING, 7)
      oprot.writeString(self.incLocation.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.incName)
    value = (value * 31) ^ hash(self.incIndustry)
    value = (value * 31) ^ hash(self.incType)
    value = (value * 31) ^ hash(self.incScale)
    value = (value * 31) ^ hash(self.incIntro)
    value = (value * 31) ^ hash(self.incUrl)
    value = (value * 31) ^ hash(self.incLocation)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdJobRaw(object):
  """
  Attributes:
   - jobPosition: 职位名称
   - jobSalaryMin: 薪水
   - jobSalaryMax: 薪水
   - jobWorkLoc: 工作地区
   - jobDiploma: 学历要求
   - jobDescription: 工作描述
   - jobCate: 职能
   - jobType: 工作类型
   - jobWelfare: 工作福利
   - gender: 性别要求
   - minAge: 年龄要求
   - maxAge: 年龄要求
   - certList: 证书要求(如:英语四六级等级证书)
   - jobMajorList: 专业要求
   - skillList: 技能要求
   - workDemand: 工作要求
   - workDuty: 工作职责
   - jobWorkAgeMin: 工作经验
   - jobWorkAgeMax: 工作经验
   - other: 其他信息
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'jobPosition', None, None, ), # 1
    (2, TType.STRING, 'jobSalaryMin', None, None, ), # 2
    (3, TType.STRING, 'jobSalaryMax', None, None, ), # 3
    (4, TType.STRING, 'jobWorkLoc', None, None, ), # 4
    (5, TType.STRING, 'jobDiploma', None, None, ), # 5
    None, # 6
    (7, TType.STRING, 'jobDescription', None, None, ), # 7
    (8, TType.STRING, 'jobCate', None, None, ), # 8
    (9, TType.STRING, 'jobType', None, None, ), # 9
    (10, TType.STRING, 'jobWelfare', None, None, ), # 10
    (11, TType.STRING, 'gender', None, None, ), # 11
    (12, TType.STRING, 'minAge', None, None, ), # 12
    (13, TType.STRING, 'maxAge', None, None, ), # 13
    (14, TType.LIST, 'certList', (TType.STRING,None), None, ), # 14
    (15, TType.LIST, 'jobMajorList', (TType.STRING,None), None, ), # 15
    (16, TType.LIST, 'skillList', (TType.STRING,None), None, ), # 16
    (17, TType.STRING, 'workDemand', None, None, ), # 17
    (18, TType.STRING, 'workDuty', None, None, ), # 18
    None, # 19
    (20, TType.STRING, 'jobWorkAgeMin', None, None, ), # 20
    (21, TType.STRING, 'jobWorkAgeMax', None, None, ), # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    None, # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    None, # 40
    None, # 41
    None, # 42
    None, # 43
    None, # 44
    None, # 45
    None, # 46
    None, # 47
    None, # 48
    None, # 49
    None, # 50
    None, # 51
    None, # 52
    None, # 53
    None, # 54
    None, # 55
    None, # 56
    None, # 57
    None, # 58
    None, # 59
    None, # 60
    None, # 61
    None, # 62
    None, # 63
    None, # 64
    None, # 65
    None, # 66
    None, # 67
    None, # 68
    None, # 69
    None, # 70
    None, # 71
    None, # 72
    None, # 73
    None, # 74
    None, # 75
    None, # 76
    None, # 77
    None, # 78
    None, # 79
    None, # 80
    None, # 81
    None, # 82
    None, # 83
    None, # 84
    None, # 85
    None, # 86
    None, # 87
    None, # 88
    None, # 89
    None, # 90
    None, # 91
    None, # 92
    None, # 93
    None, # 94
    None, # 95
    None, # 96
    None, # 97
    None, # 98
    None, # 99
    (100, TType.STRING, 'other', None, None, ), # 100
  )

  def __init__(self, jobPosition=None, jobSalaryMin=None, jobSalaryMax=None, jobWorkLoc=None, jobDiploma=None, jobDescription=None, jobCate=None, jobType=None, jobWelfare=None, gender=None, minAge=None, maxAge=None, certList=None, jobMajorList=None, skillList=None, workDemand=None, workDuty=None, jobWorkAgeMin=None, jobWorkAgeMax=None, other=None,):
    self.jobPosition = jobPosition
    self.jobSalaryMin = jobSalaryMin
    self.jobSalaryMax = jobSalaryMax
    self.jobWorkLoc = jobWorkLoc
    self.jobDiploma = jobDiploma
    self.jobDescription = jobDescription
    self.jobCate = jobCate
    self.jobType = jobType
    self.jobWelfare = jobWelfare
    self.gender = gender
    self.minAge = minAge
    self.maxAge = maxAge
    self.certList = certList
    self.jobMajorList = jobMajorList
    self.skillList = skillList
    self.workDemand = workDemand
    self.workDuty = workDuty
    self.jobWorkAgeMin = jobWorkAgeMin
    self.jobWorkAgeMax = jobWorkAgeMax
    self.other = other

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.jobPosition = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.jobSalaryMin = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.jobSalaryMax = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.jobWorkLoc = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.jobDiploma = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.STRING:
          self.jobDescription = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.jobCate = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.jobType = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.jobWelfare = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.gender = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.minAge = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.STRING:
          self.maxAge = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.LIST:
          self.certList = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = iprot.readString().decode('utf-8')
            self.certList.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.LIST:
          self.jobMajorList = []
          (_etype9, _size6) = iprot.readListBegin()
          for _i10 in xrange(_size6):
            _elem11 = iprot.readString().decode('utf-8')
            self.jobMajorList.append(_elem11)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.LIST:
          self.skillList = []
          (_etype15, _size12) = iprot.readListBegin()
          for _i16 in xrange(_size12):
            _elem17 = iprot.readString().decode('utf-8')
            self.skillList.append(_elem17)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRING:
          self.workDemand = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.STRING:
          self.workDuty = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRING:
          self.jobWorkAgeMin = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 21:
        if ftype == TType.STRING:
          self.jobWorkAgeMax = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 100:
        if ftype == TType.STRING:
          self.other = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdJobRaw')
    if self.jobPosition is not None:
      oprot.writeFieldBegin('jobPosition', TType.STRING, 1)
      oprot.writeString(self.jobPosition.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobSalaryMin is not None:
      oprot.writeFieldBegin('jobSalaryMin', TType.STRING, 2)
      oprot.writeString(self.jobSalaryMin.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobSalaryMax is not None:
      oprot.writeFieldBegin('jobSalaryMax', TType.STRING, 3)
      oprot.writeString(self.jobSalaryMax.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWorkLoc is not None:
      oprot.writeFieldBegin('jobWorkLoc', TType.STRING, 4)
      oprot.writeString(self.jobWorkLoc.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDiploma is not None:
      oprot.writeFieldBegin('jobDiploma', TType.STRING, 5)
      oprot.writeString(self.jobDiploma.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDescription is not None:
      oprot.writeFieldBegin('jobDescription', TType.STRING, 7)
      oprot.writeString(self.jobDescription.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobCate is not None:
      oprot.writeFieldBegin('jobCate', TType.STRING, 8)
      oprot.writeString(self.jobCate.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobType is not None:
      oprot.writeFieldBegin('jobType', TType.STRING, 9)
      oprot.writeString(self.jobType.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWelfare is not None:
      oprot.writeFieldBegin('jobWelfare', TType.STRING, 10)
      oprot.writeString(self.jobWelfare.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.gender is not None:
      oprot.writeFieldBegin('gender', TType.STRING, 11)
      oprot.writeString(self.gender.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.minAge is not None:
      oprot.writeFieldBegin('minAge', TType.STRING, 12)
      oprot.writeString(self.minAge.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.maxAge is not None:
      oprot.writeFieldBegin('maxAge', TType.STRING, 13)
      oprot.writeString(self.maxAge.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.certList is not None:
      oprot.writeFieldBegin('certList', TType.LIST, 14)
      oprot.writeListBegin(TType.STRING, len(self.certList))
      for iter18 in self.certList:
        oprot.writeString(iter18.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.jobMajorList is not None:
      oprot.writeFieldBegin('jobMajorList', TType.LIST, 15)
      oprot.writeListBegin(TType.STRING, len(self.jobMajorList))
      for iter19 in self.jobMajorList:
        oprot.writeString(iter19.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.skillList is not None:
      oprot.writeFieldBegin('skillList', TType.LIST, 16)
      oprot.writeListBegin(TType.STRING, len(self.skillList))
      for iter20 in self.skillList:
        oprot.writeString(iter20.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.workDemand is not None:
      oprot.writeFieldBegin('workDemand', TType.STRING, 17)
      oprot.writeString(self.workDemand.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.workDuty is not None:
      oprot.writeFieldBegin('workDuty', TType.STRING, 18)
      oprot.writeString(self.workDuty.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWorkAgeMin is not None:
      oprot.writeFieldBegin('jobWorkAgeMin', TType.STRING, 20)
      oprot.writeString(self.jobWorkAgeMin.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWorkAgeMax is not None:
      oprot.writeFieldBegin('jobWorkAgeMax', TType.STRING, 21)
      oprot.writeString(self.jobWorkAgeMax.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.other is not None:
      oprot.writeFieldBegin('other', TType.STRING, 100)
      oprot.writeString(self.other.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jobPosition)
    value = (value * 31) ^ hash(self.jobSalaryMin)
    value = (value * 31) ^ hash(self.jobSalaryMax)
    value = (value * 31) ^ hash(self.jobWorkLoc)
    value = (value * 31) ^ hash(self.jobDiploma)
    value = (value * 31) ^ hash(self.jobDescription)
    value = (value * 31) ^ hash(self.jobCate)
    value = (value * 31) ^ hash(self.jobType)
    value = (value * 31) ^ hash(self.jobWelfare)
    value = (value * 31) ^ hash(self.gender)
    value = (value * 31) ^ hash(self.minAge)
    value = (value * 31) ^ hash(self.maxAge)
    value = (value * 31) ^ hash(self.certList)
    value = (value * 31) ^ hash(self.jobMajorList)
    value = (value * 31) ^ hash(self.skillList)
    value = (value * 31) ^ hash(self.workDemand)
    value = (value * 31) ^ hash(self.workDuty)
    value = (value * 31) ^ hash(self.jobWorkAgeMin)
    value = (value * 31) ^ hash(self.jobWorkAgeMax)
    value = (value * 31) ^ hash(self.other)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdRaw(object):
  """
  Attributes:
   - jdId
   - jdFrom
   - jdUrl
   - jdInc
   - jdJob
   - pubTime
   - endTime
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'jdId', None, None, ), # 1
    (2, TType.STRING, 'jdFrom', None, None, ), # 2
    (3, TType.STRING, 'jdUrl', None, None, ), # 3
    (4, TType.STRUCT, 'jdInc', (JdIncRaw, JdIncRaw.thrift_spec), None, ), # 4
    (5, TType.STRUCT, 'jdJob', (JdJobRaw, JdJobRaw.thrift_spec), None, ), # 5
    None, # 6
    None, # 7
    (8, TType.STRING, 'pubTime', None, None, ), # 8
    (9, TType.STRING, 'endTime', None, None, ), # 9
  )

  def __init__(self, jdId=None, jdFrom=None, jdUrl=None, jdInc=None, jdJob=None, pubTime=None, endTime=None,):
    self.jdId = jdId
    self.jdFrom = jdFrom
    self.jdUrl = jdUrl
    self.jdInc = jdInc
    self.jdJob = jdJob
    self.pubTime = pubTime
    self.endTime = endTime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.jdId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.jdFrom = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.jdUrl = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.jdInc = JdIncRaw()
          self.jdInc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRUCT:
          self.jdJob = JdJobRaw()
          self.jdJob.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.pubTime = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.endTime = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdRaw')
    if self.jdId is not None:
      oprot.writeFieldBegin('jdId', TType.STRING, 1)
      oprot.writeString(self.jdId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdFrom is not None:
      oprot.writeFieldBegin('jdFrom', TType.STRING, 2)
      oprot.writeString(self.jdFrom.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdUrl is not None:
      oprot.writeFieldBegin('jdUrl', TType.STRING, 3)
      oprot.writeString(self.jdUrl.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdInc is not None:
      oprot.writeFieldBegin('jdInc', TType.STRUCT, 4)
      self.jdInc.write(oprot)
      oprot.writeFieldEnd()
    if self.jdJob is not None:
      oprot.writeFieldBegin('jdJob', TType.STRUCT, 5)
      self.jdJob.write(oprot)
      oprot.writeFieldEnd()
    if self.pubTime is not None:
      oprot.writeFieldBegin('pubTime', TType.STRING, 8)
      oprot.writeString(self.pubTime.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.endTime is not None:
      oprot.writeFieldBegin('endTime', TType.STRING, 9)
      oprot.writeString(self.endTime.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jdId)
    value = (value * 31) ^ hash(self.jdFrom)
    value = (value * 31) ^ hash(self.jdUrl)
    value = (value * 31) ^ hash(self.jdInc)
    value = (value * 31) ^ hash(self.jdJob)
    value = (value * 31) ^ hash(self.pubTime)
    value = (value * 31) ^ hash(self.endTime)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdIncMeasure(object):
  """
  Attributes:
   - incSegmentId: 公司片段id
   - incIndustryId: 公司行业
   - incType: 公司类型
   - incScaleMin: 公司规模最小值
   - incScaleMax: 公司规模最大值
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'incSegmentId', None, None, ), # 1
    (2, TType.BYTE, 'incIndustryId', None, None, ), # 2
    (3, TType.BYTE, 'incType', None, None, ), # 3
    (4, TType.I32, 'incScaleMin', None, None, ), # 4
    (5, TType.I32, 'incScaleMax', None, None, ), # 5
  )

  def __init__(self, incSegmentId=None, incIndustryId=None, incType=None, incScaleMin=None, incScaleMax=None,):
    self.incSegmentId = incSegmentId
    self.incIndustryId = incIndustryId
    self.incType = incType
    self.incScaleMin = incScaleMin
    self.incScaleMax = incScaleMax

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.incSegmentId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BYTE:
          self.incIndustryId = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BYTE:
          self.incType = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.incScaleMin = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.incScaleMax = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdIncMeasure')
    if self.incSegmentId is not None:
      oprot.writeFieldBegin('incSegmentId', TType.STRING, 1)
      oprot.writeString(self.incSegmentId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incIndustryId is not None:
      oprot.writeFieldBegin('incIndustryId', TType.BYTE, 2)
      oprot.writeByte(self.incIndustryId)
      oprot.writeFieldEnd()
    if self.incType is not None:
      oprot.writeFieldBegin('incType', TType.BYTE, 3)
      oprot.writeByte(self.incType)
      oprot.writeFieldEnd()
    if self.incScaleMin is not None:
      oprot.writeFieldBegin('incScaleMin', TType.I32, 4)
      oprot.writeI32(self.incScaleMin)
      oprot.writeFieldEnd()
    if self.incScaleMax is not None:
      oprot.writeFieldBegin('incScaleMax', TType.I32, 5)
      oprot.writeI32(self.incScaleMax)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.incSegmentId)
    value = (value * 31) ^ hash(self.incIndustryId)
    value = (value * 31) ^ hash(self.incType)
    value = (value * 31) ^ hash(self.incScaleMin)
    value = (value * 31) ^ hash(self.incScaleMax)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdJobMeasure(object):
  """
  Attributes:
   - jobSalaryMin: 薪水最小值
   - jobSalaryMax: 薪水最大值
   - jobWorkLocId: 工作地区
   - jobDiplomaId: 学历
   - jobWorkAgeMin: 工作经历最小值
   - jobWorkAgeMax: 工作经历最大值
   - jobPosition: 职位名称
   - jobDescription: 工作描述
   - jobCate: 职位职能
   - jobType: 工作类型　
   - jobWelfare: 工作福利　
   - jobMajorList: 专业　
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'jobSalaryMin', None, None, ), # 1
    (2, TType.I32, 'jobSalaryMax', None, None, ), # 2
    (3, TType.STRING, 'jobWorkLocId', None, None, ), # 3
    (4, TType.BYTE, 'jobDiplomaId', None, None, ), # 4
    (5, TType.I64, 'jobWorkAgeMin', None, None, ), # 5
    (6, TType.I64, 'jobWorkAgeMax', None, None, ), # 6
    None, # 7
    (8, TType.STRING, 'jobPosition', None, None, ), # 8
    (9, TType.STRING, 'jobDescription', None, None, ), # 9
    (10, TType.STRING, 'jobCate', None, None, ), # 10
    (11, TType.STRING, 'jobType', None, None, ), # 11
    (12, TType.STRING, 'jobWelfare', None, None, ), # 12
    (13, TType.LIST, 'jobMajorList', (TType.STRING,None), None, ), # 13
  )

  def __init__(self, jobSalaryMin=None, jobSalaryMax=None, jobWorkLocId=None, jobDiplomaId=None, jobWorkAgeMin=None, jobWorkAgeMax=None, jobPosition=None, jobDescription=None, jobCate=None, jobType=None, jobWelfare=None, jobMajorList=None,):
    self.jobSalaryMin = jobSalaryMin
    self.jobSalaryMax = jobSalaryMax
    self.jobWorkLocId = jobWorkLocId
    self.jobDiplomaId = jobDiplomaId
    self.jobWorkAgeMin = jobWorkAgeMin
    self.jobWorkAgeMax = jobWorkAgeMax
    self.jobPosition = jobPosition
    self.jobDescription = jobDescription
    self.jobCate = jobCate
    self.jobType = jobType
    self.jobWelfare = jobWelfare
    self.jobMajorList = jobMajorList

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.jobSalaryMin = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.jobSalaryMax = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.jobWorkLocId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.BYTE:
          self.jobDiplomaId = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I64:
          self.jobWorkAgeMin = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I64:
          self.jobWorkAgeMax = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRING:
          self.jobPosition = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.STRING:
          self.jobDescription = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.STRING:
          self.jobCate = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.STRING:
          self.jobType = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.jobWelfare = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.LIST:
          self.jobMajorList = []
          (_etype24, _size21) = iprot.readListBegin()
          for _i25 in xrange(_size21):
            _elem26 = iprot.readString().decode('utf-8')
            self.jobMajorList.append(_elem26)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdJobMeasure')
    if self.jobSalaryMin is not None:
      oprot.writeFieldBegin('jobSalaryMin', TType.I32, 1)
      oprot.writeI32(self.jobSalaryMin)
      oprot.writeFieldEnd()
    if self.jobSalaryMax is not None:
      oprot.writeFieldBegin('jobSalaryMax', TType.I32, 2)
      oprot.writeI32(self.jobSalaryMax)
      oprot.writeFieldEnd()
    if self.jobWorkLocId is not None:
      oprot.writeFieldBegin('jobWorkLocId', TType.STRING, 3)
      oprot.writeString(self.jobWorkLocId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDiplomaId is not None:
      oprot.writeFieldBegin('jobDiplomaId', TType.BYTE, 4)
      oprot.writeByte(self.jobDiplomaId)
      oprot.writeFieldEnd()
    if self.jobWorkAgeMin is not None:
      oprot.writeFieldBegin('jobWorkAgeMin', TType.I64, 5)
      oprot.writeI64(self.jobWorkAgeMin)
      oprot.writeFieldEnd()
    if self.jobWorkAgeMax is not None:
      oprot.writeFieldBegin('jobWorkAgeMax', TType.I64, 6)
      oprot.writeI64(self.jobWorkAgeMax)
      oprot.writeFieldEnd()
    if self.jobPosition is not None:
      oprot.writeFieldBegin('jobPosition', TType.STRING, 8)
      oprot.writeString(self.jobPosition.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDescription is not None:
      oprot.writeFieldBegin('jobDescription', TType.STRING, 9)
      oprot.writeString(self.jobDescription.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobCate is not None:
      oprot.writeFieldBegin('jobCate', TType.STRING, 10)
      oprot.writeString(self.jobCate.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobType is not None:
      oprot.writeFieldBegin('jobType', TType.STRING, 11)
      oprot.writeString(self.jobType.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWelfare is not None:
      oprot.writeFieldBegin('jobWelfare', TType.STRING, 12)
      oprot.writeString(self.jobWelfare.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobMajorList is not None:
      oprot.writeFieldBegin('jobMajorList', TType.LIST, 13)
      oprot.writeListBegin(TType.STRING, len(self.jobMajorList))
      for iter27 in self.jobMajorList:
        oprot.writeString(iter27.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jobSalaryMin)
    value = (value * 31) ^ hash(self.jobSalaryMax)
    value = (value * 31) ^ hash(self.jobWorkLocId)
    value = (value * 31) ^ hash(self.jobDiplomaId)
    value = (value * 31) ^ hash(self.jobWorkAgeMin)
    value = (value * 31) ^ hash(self.jobWorkAgeMax)
    value = (value * 31) ^ hash(self.jobPosition)
    value = (value * 31) ^ hash(self.jobDescription)
    value = (value * 31) ^ hash(self.jobCate)
    value = (value * 31) ^ hash(self.jobType)
    value = (value * 31) ^ hash(self.jobWelfare)
    value = (value * 31) ^ hash(self.jobMajorList)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdMeasure(object):
  """
  Attributes:
   - jdId
   - jdFrom
   - jdUrl
   - jdInc
   - jdJob
   - pubDate
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'jdId', None, None, ), # 1
    (2, TType.STRING, 'jdFrom', None, None, ), # 2
    (3, TType.STRING, 'jdUrl', None, None, ), # 3
    (4, TType.STRUCT, 'jdInc', (JdIncMeasure, JdIncMeasure.thrift_spec), None, ), # 4
    (5, TType.STRUCT, 'jdJob', (JdJobMeasure, JdJobMeasure.thrift_spec), None, ), # 5
    None, # 6
    None, # 7
    (8, TType.I64, 'pubDate', None, None, ), # 8
  )

  def __init__(self, jdId=None, jdFrom=None, jdUrl=None, jdInc=None, jdJob=None, pubDate=None,):
    self.jdId = jdId
    self.jdFrom = jdFrom
    self.jdUrl = jdUrl
    self.jdInc = jdInc
    self.jdJob = jdJob
    self.pubDate = pubDate

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.jdId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.jdFrom = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.jdUrl = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.jdInc = JdIncMeasure()
          self.jdInc.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRUCT:
          self.jdJob = JdJobMeasure()
          self.jdJob.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I64:
          self.pubDate = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdMeasure')
    if self.jdId is not None:
      oprot.writeFieldBegin('jdId', TType.STRING, 1)
      oprot.writeString(self.jdId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdFrom is not None:
      oprot.writeFieldBegin('jdFrom', TType.STRING, 2)
      oprot.writeString(self.jdFrom.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdUrl is not None:
      oprot.writeFieldBegin('jdUrl', TType.STRING, 3)
      oprot.writeString(self.jdUrl.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jdInc is not None:
      oprot.writeFieldBegin('jdInc', TType.STRUCT, 4)
      self.jdInc.write(oprot)
      oprot.writeFieldEnd()
    if self.jdJob is not None:
      oprot.writeFieldBegin('jdJob', TType.STRUCT, 5)
      self.jdJob.write(oprot)
      oprot.writeFieldEnd()
    if self.pubDate is not None:
      oprot.writeFieldBegin('pubDate', TType.I64, 8)
      oprot.writeI64(self.pubDate)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jdId)
    value = (value * 31) ^ hash(self.jdFrom)
    value = (value * 31) ^ hash(self.jdUrl)
    value = (value * 31) ^ hash(self.jdInc)
    value = (value * 31) ^ hash(self.jdJob)
    value = (value * 31) ^ hash(self.pubDate)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdMergedInfo(object):
  """
  Attributes:
   - jdMergedId
   - uid
   - pubDateStamp
   - rawJdList
   - incSegmentId
   - incIndustryId
   - incType
   - incScaleMin
   - incScaleMax
   - jobSalaryMin
   - jobSalaryMax
   - jobWorkLocId
   - jobDiplomaId
   - jobWorkAgeMin
   - jobWorkAgeMax
   - jobPosition
   - jobDescription
   - jobCate
   - jobType
   - jobWelfare
   - jobMajor
   - skillList
   - workDemand
   - workDuty
   - jobTagList
   - status
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'jdMergedId', None, None, ), # 1
    (2, TType.I32, 'uid', None, None, ), # 2
    (3, TType.I64, 'pubDateStamp', None, None, ), # 3
    (4, TType.LIST, 'rawJdList', (TType.STRING,None), None, ), # 4
    (5, TType.STRING, 'incSegmentId', None, None, ), # 5
    (6, TType.BYTE, 'incIndustryId', None, None, ), # 6
    (7, TType.BYTE, 'incType', None, None, ), # 7
    (8, TType.I32, 'incScaleMin', None, None, ), # 8
    (9, TType.I32, 'incScaleMax', None, None, ), # 9
    (10, TType.I32, 'jobSalaryMin', None, None, ), # 10
    (11, TType.I32, 'jobSalaryMax', None, None, ), # 11
    (12, TType.STRING, 'jobWorkLocId', None, None, ), # 12
    (13, TType.BYTE, 'jobDiplomaId', None, None, ), # 13
    (14, TType.I64, 'jobWorkAgeMin', None, None, ), # 14
    (15, TType.I64, 'jobWorkAgeMax', None, None, ), # 15
    (16, TType.STRING, 'jobPosition', None, None, ), # 16
    (17, TType.STRING, 'jobDescription', None, None, ), # 17
    (18, TType.STRING, 'jobCate', None, None, ), # 18
    (19, TType.STRING, 'jobType', None, None, ), # 19
    None, # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    None, # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    None, # 40
    None, # 41
    None, # 42
    None, # 43
    None, # 44
    None, # 45
    None, # 46
    None, # 47
    None, # 48
    None, # 49
    (50, TType.STRING, 'jobWelfare', None, None, ), # 50
    (51, TType.STRING, 'jobMajor', None, None, ), # 51
    (52, TType.LIST, 'skillList', (TType.STRING,None), None, ), # 52
    (53, TType.STRING, 'workDemand', None, None, ), # 53
    (54, TType.STRING, 'workDuty', None, None, ), # 54
    (55, TType.LIST, 'jobTagList', (TType.STRING,None), None, ), # 55
    None, # 56
    None, # 57
    None, # 58
    None, # 59
    None, # 60
    None, # 61
    None, # 62
    None, # 63
    None, # 64
    None, # 65
    None, # 66
    None, # 67
    None, # 68
    None, # 69
    None, # 70
    None, # 71
    None, # 72
    None, # 73
    None, # 74
    None, # 75
    None, # 76
    None, # 77
    None, # 78
    None, # 79
    None, # 80
    None, # 81
    None, # 82
    None, # 83
    None, # 84
    None, # 85
    None, # 86
    None, # 87
    None, # 88
    None, # 89
    None, # 90
    None, # 91
    None, # 92
    None, # 93
    None, # 94
    None, # 95
    None, # 96
    None, # 97
    None, # 98
    None, # 99
    (100, TType.I32, 'status', None, None, ), # 100
  )

  def __init__(self, jdMergedId=None, uid=None, pubDateStamp=None, rawJdList=None, incSegmentId=None, incIndustryId=None, incType=None, incScaleMin=None, incScaleMax=None, jobSalaryMin=None, jobSalaryMax=None, jobWorkLocId=None, jobDiplomaId=None, jobWorkAgeMin=None, jobWorkAgeMax=None, jobPosition=None, jobDescription=None, jobCate=None, jobType=None, jobWelfare=None, jobMajor=None, skillList=None, workDemand=None, workDuty=None, jobTagList=None, status=None,):
    self.jdMergedId = jdMergedId
    self.uid = uid
    self.pubDateStamp = pubDateStamp
    self.rawJdList = rawJdList
    self.incSegmentId = incSegmentId
    self.incIndustryId = incIndustryId
    self.incType = incType
    self.incScaleMin = incScaleMin
    self.incScaleMax = incScaleMax
    self.jobSalaryMin = jobSalaryMin
    self.jobSalaryMax = jobSalaryMax
    self.jobWorkLocId = jobWorkLocId
    self.jobDiplomaId = jobDiplomaId
    self.jobWorkAgeMin = jobWorkAgeMin
    self.jobWorkAgeMax = jobWorkAgeMax
    self.jobPosition = jobPosition
    self.jobDescription = jobDescription
    self.jobCate = jobCate
    self.jobType = jobType
    self.jobWelfare = jobWelfare
    self.jobMajor = jobMajor
    self.skillList = skillList
    self.workDemand = workDemand
    self.workDuty = workDuty
    self.jobTagList = jobTagList
    self.status = status

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.jdMergedId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.uid = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I64:
          self.pubDateStamp = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.rawJdList = []
          (_etype31, _size28) = iprot.readListBegin()
          for _i32 in xrange(_size28):
            _elem33 = iprot.readString().decode('utf-8')
            self.rawJdList.append(_elem33)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.incSegmentId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.BYTE:
          self.incIndustryId = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.BYTE:
          self.incType = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I32:
          self.incScaleMin = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I32:
          self.incScaleMax = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I32:
          self.jobSalaryMin = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 11:
        if ftype == TType.I32:
          self.jobSalaryMax = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 12:
        if ftype == TType.STRING:
          self.jobWorkLocId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 13:
        if ftype == TType.BYTE:
          self.jobDiplomaId = iprot.readByte();
        else:
          iprot.skip(ftype)
      elif fid == 14:
        if ftype == TType.I64:
          self.jobWorkAgeMin = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 15:
        if ftype == TType.I64:
          self.jobWorkAgeMax = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 16:
        if ftype == TType.STRING:
          self.jobPosition = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 17:
        if ftype == TType.STRING:
          self.jobDescription = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 18:
        if ftype == TType.STRING:
          self.jobCate = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 19:
        if ftype == TType.STRING:
          self.jobType = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 50:
        if ftype == TType.STRING:
          self.jobWelfare = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 51:
        if ftype == TType.STRING:
          self.jobMajor = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 52:
        if ftype == TType.LIST:
          self.skillList = []
          (_etype37, _size34) = iprot.readListBegin()
          for _i38 in xrange(_size34):
            _elem39 = iprot.readString().decode('utf-8')
            self.skillList.append(_elem39)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 53:
        if ftype == TType.STRING:
          self.workDemand = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 54:
        if ftype == TType.STRING:
          self.workDuty = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 55:
        if ftype == TType.LIST:
          self.jobTagList = []
          (_etype43, _size40) = iprot.readListBegin()
          for _i44 in xrange(_size40):
            _elem45 = iprot.readString().decode('utf-8')
            self.jobTagList.append(_elem45)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 100:
        if ftype == TType.I32:
          self.status = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdMergedInfo')
    if self.jdMergedId is not None:
      oprot.writeFieldBegin('jdMergedId', TType.STRING, 1)
      oprot.writeString(self.jdMergedId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I32, 2)
      oprot.writeI32(self.uid)
      oprot.writeFieldEnd()
    if self.pubDateStamp is not None:
      oprot.writeFieldBegin('pubDateStamp', TType.I64, 3)
      oprot.writeI64(self.pubDateStamp)
      oprot.writeFieldEnd()
    if self.rawJdList is not None:
      oprot.writeFieldBegin('rawJdList', TType.LIST, 4)
      oprot.writeListBegin(TType.STRING, len(self.rawJdList))
      for iter46 in self.rawJdList:
        oprot.writeString(iter46.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.incSegmentId is not None:
      oprot.writeFieldBegin('incSegmentId', TType.STRING, 5)
      oprot.writeString(self.incSegmentId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.incIndustryId is not None:
      oprot.writeFieldBegin('incIndustryId', TType.BYTE, 6)
      oprot.writeByte(self.incIndustryId)
      oprot.writeFieldEnd()
    if self.incType is not None:
      oprot.writeFieldBegin('incType', TType.BYTE, 7)
      oprot.writeByte(self.incType)
      oprot.writeFieldEnd()
    if self.incScaleMin is not None:
      oprot.writeFieldBegin('incScaleMin', TType.I32, 8)
      oprot.writeI32(self.incScaleMin)
      oprot.writeFieldEnd()
    if self.incScaleMax is not None:
      oprot.writeFieldBegin('incScaleMax', TType.I32, 9)
      oprot.writeI32(self.incScaleMax)
      oprot.writeFieldEnd()
    if self.jobSalaryMin is not None:
      oprot.writeFieldBegin('jobSalaryMin', TType.I32, 10)
      oprot.writeI32(self.jobSalaryMin)
      oprot.writeFieldEnd()
    if self.jobSalaryMax is not None:
      oprot.writeFieldBegin('jobSalaryMax', TType.I32, 11)
      oprot.writeI32(self.jobSalaryMax)
      oprot.writeFieldEnd()
    if self.jobWorkLocId is not None:
      oprot.writeFieldBegin('jobWorkLocId', TType.STRING, 12)
      oprot.writeString(self.jobWorkLocId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDiplomaId is not None:
      oprot.writeFieldBegin('jobDiplomaId', TType.BYTE, 13)
      oprot.writeByte(self.jobDiplomaId)
      oprot.writeFieldEnd()
    if self.jobWorkAgeMin is not None:
      oprot.writeFieldBegin('jobWorkAgeMin', TType.I64, 14)
      oprot.writeI64(self.jobWorkAgeMin)
      oprot.writeFieldEnd()
    if self.jobWorkAgeMax is not None:
      oprot.writeFieldBegin('jobWorkAgeMax', TType.I64, 15)
      oprot.writeI64(self.jobWorkAgeMax)
      oprot.writeFieldEnd()
    if self.jobPosition is not None:
      oprot.writeFieldBegin('jobPosition', TType.STRING, 16)
      oprot.writeString(self.jobPosition.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobDescription is not None:
      oprot.writeFieldBegin('jobDescription', TType.STRING, 17)
      oprot.writeString(self.jobDescription.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobCate is not None:
      oprot.writeFieldBegin('jobCate', TType.STRING, 18)
      oprot.writeString(self.jobCate.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobType is not None:
      oprot.writeFieldBegin('jobType', TType.STRING, 19)
      oprot.writeString(self.jobType.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobWelfare is not None:
      oprot.writeFieldBegin('jobWelfare', TType.STRING, 50)
      oprot.writeString(self.jobWelfare.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobMajor is not None:
      oprot.writeFieldBegin('jobMajor', TType.STRING, 51)
      oprot.writeString(self.jobMajor.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.skillList is not None:
      oprot.writeFieldBegin('skillList', TType.LIST, 52)
      oprot.writeListBegin(TType.STRING, len(self.skillList))
      for iter47 in self.skillList:
        oprot.writeString(iter47.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.workDemand is not None:
      oprot.writeFieldBegin('workDemand', TType.STRING, 53)
      oprot.writeString(self.workDemand.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.workDuty is not None:
      oprot.writeFieldBegin('workDuty', TType.STRING, 54)
      oprot.writeString(self.workDuty.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.jobTagList is not None:
      oprot.writeFieldBegin('jobTagList', TType.LIST, 55)
      oprot.writeListBegin(TType.STRING, len(self.jobTagList))
      for iter48 in self.jobTagList:
        oprot.writeString(iter48.encode('utf-8'))
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 100)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jdMergedId)
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.pubDateStamp)
    value = (value * 31) ^ hash(self.rawJdList)
    value = (value * 31) ^ hash(self.incSegmentId)
    value = (value * 31) ^ hash(self.incIndustryId)
    value = (value * 31) ^ hash(self.incType)
    value = (value * 31) ^ hash(self.incScaleMin)
    value = (value * 31) ^ hash(self.incScaleMax)
    value = (value * 31) ^ hash(self.jobSalaryMin)
    value = (value * 31) ^ hash(self.jobSalaryMax)
    value = (value * 31) ^ hash(self.jobWorkLocId)
    value = (value * 31) ^ hash(self.jobDiplomaId)
    value = (value * 31) ^ hash(self.jobWorkAgeMin)
    value = (value * 31) ^ hash(self.jobWorkAgeMax)
    value = (value * 31) ^ hash(self.jobPosition)
    value = (value * 31) ^ hash(self.jobDescription)
    value = (value * 31) ^ hash(self.jobCate)
    value = (value * 31) ^ hash(self.jobType)
    value = (value * 31) ^ hash(self.jobWelfare)
    value = (value * 31) ^ hash(self.jobMajor)
    value = (value * 31) ^ hash(self.skillList)
    value = (value * 31) ^ hash(self.workDemand)
    value = (value * 31) ^ hash(self.workDuty)
    value = (value * 31) ^ hash(self.jobTagList)
    value = (value * 31) ^ hash(self.status)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class JdVector(object):
  """
  Attributes:
   - jdMergedId
   - posVector
   - descVector
   - uid
   - status
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'jdMergedId', None, None, ), # 1
    (2, TType.LIST, 'posVector', (TType.DOUBLE,None), None, ), # 2
    (3, TType.LIST, 'descVector', (TType.DOUBLE,None), None, ), # 3
    (4, TType.I32, 'uid', None, None, ), # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.I32, 'status', None, None, ), # 10
  )

  def __init__(self, jdMergedId=None, posVector=None, descVector=None, uid=None, status=None,):
    self.jdMergedId = jdMergedId
    self.posVector = posVector
    self.descVector = descVector
    self.uid = uid
    self.status = status

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.jdMergedId = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.posVector = []
          (_etype52, _size49) = iprot.readListBegin()
          for _i53 in xrange(_size49):
            _elem54 = iprot.readDouble();
            self.posVector.append(_elem54)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.LIST:
          self.descVector = []
          (_etype58, _size55) = iprot.readListBegin()
          for _i59 in xrange(_size55):
            _elem60 = iprot.readDouble();
            self.descVector.append(_elem60)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.uid = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 10:
        if ftype == TType.I32:
          self.status = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('JdVector')
    if self.jdMergedId is not None:
      oprot.writeFieldBegin('jdMergedId', TType.STRING, 1)
      oprot.writeString(self.jdMergedId.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.posVector is not None:
      oprot.writeFieldBegin('posVector', TType.LIST, 2)
      oprot.writeListBegin(TType.DOUBLE, len(self.posVector))
      for iter61 in self.posVector:
        oprot.writeDouble(iter61)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.descVector is not None:
      oprot.writeFieldBegin('descVector', TType.LIST, 3)
      oprot.writeListBegin(TType.DOUBLE, len(self.descVector))
      for iter62 in self.descVector:
        oprot.writeDouble(iter62)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.uid is not None:
      oprot.writeFieldBegin('uid', TType.I32, 4)
      oprot.writeI32(self.uid)
      oprot.writeFieldEnd()
    if self.status is not None:
      oprot.writeFieldBegin('status', TType.I32, 10)
      oprot.writeI32(self.status)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.jdMergedId)
    value = (value * 31) ^ hash(self.posVector)
    value = (value * 31) ^ hash(self.descVector)
    value = (value * 31) ^ hash(self.uid)
    value = (value * 31) ^ hash(self.status)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
