# -*- coding:utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class MarriageType(object):
  MARRIAGE_SINGLE = 1
  MARRIAGE_MARRIED = 2
  MARRIAGE_DIVORCED = 3
  MARRIAGE_SECRECY = 4

  _VALUES_TO_NAMES = {
    1: "MARRIAGE_SINGLE",
    2: "MARRIAGE_MARRIED",
    3: "MARRIAGE_DIVORCED",
    4: "MARRIAGE_SECRECY",
  }

  _NAMES_TO_VALUES = {
    "MARRIAGE_SINGLE": 1,
    "MARRIAGE_MARRIED": 2,
    "MARRIAGE_DIVORCED": 3,
    "MARRIAGE_SECRECY": 4,
  }

class GenderType(object):
  GENDER_FEMALE = 0
  GENDER_MALE = 1

  _VALUES_TO_NAMES = {
    0: "GENDER_FEMALE",
    1: "GENDER_MALE",
  }

  _NAMES_TO_VALUES = {
    "GENDER_FEMALE": 0,
    "GENDER_MALE": 1,
  }

class PoliticsType(object):
  POLI_QUNZHONG = 1
  POLI_WUDANGPAI = 2
  POLI_TUANYUAN = 3
  POLI_DANGYUAN = 4
  POLI_MINZHUPAI = 5

  _VALUES_TO_NAMES = {
    1: "POLI_QUNZHONG",
    2: "POLI_WUDANGPAI",
    3: "POLI_TUANYUAN",
    4: "POLI_DANGYUAN",
    5: "POLI_MINZHUPAI",
  }

  _NAMES_TO_VALUES = {
    "POLI_QUNZHONG": 1,
    "POLI_WUDANGPAI": 2,
    "POLI_TUANYUAN": 3,
    "POLI_DANGYUAN": 4,
    "POLI_MINZHUPAI": 5,
  }

