# -*- coding:utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class IncType(object):
  INC_TYPE_OTHER = 0
  INC_TYPE_GUOQI = 1
  INC_TYPE_MINYING = 2
  INC_TYPE_HEYING = 3
  INC_TYPE_DUZI = 4
  INC_TYPE_SHANGSHI = 5
  INC_TYPE_SHIYE = 6
  INC_TYPE_JIGUAN = 7
  INC_TYPE_GUFEN = 8
  INC_TYPE_DAIBIAOCHU = 9

  _VALUES_TO_NAMES = {
    0: "INC_TYPE_OTHER",
    1: "INC_TYPE_GUOQI",
    2: "INC_TYPE_MINYING",
    3: "INC_TYPE_HEYING",
    4: "INC_TYPE_DUZI",
    5: "INC_TYPE_SHANGSHI",
    6: "INC_TYPE_SHIYE",
    7: "INC_TYPE_JIGUAN",
    8: "INC_TYPE_GUFEN",
    9: "INC_TYPE_DAIBIAOCHU",
  }

  _NAMES_TO_VALUES = {
    "INC_TYPE_OTHER": 0,
    "INC_TYPE_GUOQI": 1,
    "INC_TYPE_MINYING": 2,
    "INC_TYPE_HEYING": 3,
    "INC_TYPE_DUZI": 4,
    "INC_TYPE_SHANGSHI": 5,
    "INC_TYPE_SHIYE": 6,
    "INC_TYPE_JIGUAN": 7,
    "INC_TYPE_GUFEN": 8,
    "INC_TYPE_DAIBIAOCHU": 9,
  }

class WorkStatusType(object):
  WORK_STATUS_YINGJIE = 1
  WORK_STATUS_OFFJOB = 2
  WORK_STATUS_ONJOB1 = 3
  WORK_STATUS_ONJOB2 = 4
  WORK_STATUS_NOJUMP = 5

  _VALUES_TO_NAMES = {
    1: "WORK_STATUS_YINGJIE",
    2: "WORK_STATUS_OFFJOB",
    3: "WORK_STATUS_ONJOB1",
    4: "WORK_STATUS_ONJOB2",
    5: "WORK_STATUS_NOJUMP",
  }

  _NAMES_TO_VALUES = {
    "WORK_STATUS_YINGJIE": 1,
    "WORK_STATUS_OFFJOB": 2,
    "WORK_STATUS_ONJOB1": 3,
    "WORK_STATUS_ONJOB2": 4,
    "WORK_STATUS_NOJUMP": 5,
  }

class JobType(object):
  JOB_TYPE_QUANZHI = 1
  JOB_TYPE_SHIXI = 2
  JOB_TYPE_JIANZHI = 3
  JOB_TYPE_ALL = 4

  _VALUES_TO_NAMES = {
    1: "JOB_TYPE_QUANZHI",
    2: "JOB_TYPE_SHIXI",
    3: "JOB_TYPE_JIANZHI",
    4: "JOB_TYPE_ALL",
  }

  _NAMES_TO_VALUES = {
    "JOB_TYPE_QUANZHI": 1,
    "JOB_TYPE_SHIXI": 2,
    "JOB_TYPE_JIANZHI": 3,
    "JOB_TYPE_ALL": 4,
  }

