#!/usr/bin/env python
# coding=utf-8

__author__='jkmiao'


def leven_distance(s1,s2):
    """
    动态规划实现编辑距离
    """
    m,n = len(s1),len(s2)
    colsize,v1,v2 = m+1,[],[]

    for i in range((n+1)):
        v1.append(i)
        v2.append(i)

    for i in range(m+1)[1:m+1]:
        for j in range(n+1)[1:n+1]:
            cost = 0
            if s1[i-1]==s2[j-1]:
                cost = 0
            else:
                cost = 1
            minValue = v1[j]+1
            if minValue > v2[j-1]+1:
                minValue = v2[j-1]+1
            if minValue >v1[j-1]+cost:
                minValue = v1[j-1]+cost
            v2[j] = minValue
        for j in range(n+1):
            v1[j] = v2[j]
    print v2[n]

    return v2[n]


leven_distance(u'PHP高技术前端开发',u'php前端工程师')
