# -*- coding:utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class VectorType(object):
  JOB_POSITION_RECOMMEND_VEC = 1
  JOB_DESC_RECOMMEND_VEC = 2

  _VALUES_TO_NAMES = {
    1: "JOB_POSITION_RECOMMEND_VEC",
    2: "JOB_DESC_RECOMMEND_VEC",
  }

  _NAMES_TO_VALUES = {
    "JOB_POSITION_RECOMMEND_VEC": 1,
    "JOB_DESC_RECOMMEND_VEC": 2,
  }

